contact_links:
  - name: Discussions
    url: https://github.com/amenocal/open-source-demo/discussions
    about: Please ask and answer questions here
  - name: Security Vulnerability
    url: https://github.com/amenocal/open-source-demo/security/policy
    about: Please report security vulnerabilities as directed by our security policy
