name: Documentation Improvement
description: Suggest improvements to our documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!
  - type: textarea
    id: documentation-issue
    attributes:
      label: Documentation Issue
      description: Describe what's missing, unclear, or incorrect in the documentation
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where did you find this documentation issue? Provide links or paths
    validations:
      required: true
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your suggestion
    validations:
      required: false
