name: Continuous Integration

on:
    pull_request:
      branches: [main]

permissions:
  contents: read # Allow the workflow to read the repository contents

jobs:

  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...